version: '3.8'

networks:
  localstack-net:
    name: localstack-net
    driver: bridge

services:
  localstack:
    image: localstack/localstack
    privileged: true
    networks:
      - localstack-net
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=sqs,dynamodb,s3
      - DO_NOT_REUSE_DATA=1
      - DEFAULT_REGION=eu-west-1
    volumes:
      - ./.volumes/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
# volumes:
#   localstack-data:
#     driver: local
#     # external: true



