version: '3.8'
# Launch only the database
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  db-postgresql:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=mytemplate
    volumes:
      # - ./data/postgres:/var/lib/postgresql/data
      - postgres-data:/var/lib/postgresql/data
  db-mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    # image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Replication_2024
      - MYSQL_DATABASE=mytemplate
      - MYSQL_USER=test
      - MYSQL_PASSWORD=Replication_2024
      - MYSQL_LOG_BIN=1
    volumes:
      - mysql-data:/var/lib/mysql
      # - ./mysql-conf.d:/etc/mysql/conf.d
  db-mysql8:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Replication_2024
      - MYSQL_DATABASE=mytemplate
      - MYSQL_USER=test
      - MYSQL_PASSWORD=Replication_2024
    volumes:
      - mysql8-data:/var/lib/mysql

volumes:
  postgres-data:
    driver: local
    # external: true
  redis-data:
    driver: local
    # external: true
  mysql-data:
    driver: local
    # external: true
  mysql8-data:
    driver: local
