"""create test permissions data

Revision ID: 1953ae5a140b
Revises: 5b4b80397e51
Create Date: 2024-10-01 15:33:08.013415

"""

from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
from faker import Faker
from ksuid import Ksuid

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1953ae5a140b"
down_revision: Union[str, None] = "5b4b80397e51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    id: str = str(Ksuid())
    name: str = "wttest"
    created_by: str = "FAKE"
    created_at: str = datetime.now().isoformat()
    op.execute(
        f"INSERT INTO public.permissions (id, username, permission, created_by, created_at, updated_by, updated_at) VALUES('{id}', '{name}', 'persons.list', '{created_by}', '{created_at}', '{created_by}', '{created_at}');"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
