"""Added currency field to policies

Revision ID: c266645c98b8
Revises: dfd56f85dfaf
Create Date: 2024-09-24 15:26:38.430304

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c266645c98b8"
down_revision: Union[str, None] = "dfd56f85dfaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the new enum type
currency_enum = postgresql.ENUM("USD", "EUR", "GBP", name="currencyenum")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add manually the new enum type
    currency_enum.create(op.get_bind())

    op.add_column(
        "policies",
        sa.Column(
            "currency",
            sa.Enum("EUR", "USD", "GBP", "JPY", "CHF", name="currencyenum"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("policies", "currency")
    # ### end Alembic commands ###
