"""Initial migration

Revision ID: cc8e6fbfe8d7
Revises: 
Create Date: 2024-09-26 13:57:02.655947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8e6fbfe8d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.String(length=27), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('surname', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('identification_number', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identification_number')
    )
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.String(length=27), nullable=False),
    sa.Column('street', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=500), nullable=False),
    sa.Column('postal_code', sa.String(length=500), nullable=False),
    sa.Column('province', sa.String(length=500), nullable=False),
    sa.Column('country', sa.String(length=500), nullable=False),
    sa.Column('person_id', sa.String(length=27), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.String(length=27), nullable=False),
    sa.Column('holder_id', sa.String(length=27), nullable=False),
    sa.Column('policy_number', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'VALIDATED', 'ACTIVE', 'INACTIVE', 'CANCELLED', 'EXPIRED', name='policystatusenum'), nullable=False),
    sa.Column('policy_type', sa.Enum('HOME', 'LIFE', 'CAR', 'CONTENTS', name='policytypeenum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('EUR', 'USD', 'GBP', 'JPY', 'CHF', name='currencyenum'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['holder_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
