"""Added concurrency control fields

Revision ID: da31cc8c410c
Revises: 1953ae5a140b
Create Date: 2024-10-15 12:22:20.363925

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da31cc8c410c"
down_revision: Union[str, None] = "1953ae5a140b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "addresses", "created_at", existing_type=sa.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "addresses", "updated_at", existing_type=sa.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "permissions", "created_at", existing_type=sa.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "permissions", "updated_at", existing_type=sa.TIMESTAMP(), nullable=False
    )
    op.add_column(
        "persons",
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
    )
    op.alter_column(
        "persons", "created_at", existing_type=sa.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "persons", "updated_at", existing_type=sa.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "policies", "created_at", existing_type=sa.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "policies", "updated_at", existing_type=sa.TIMESTAMP(), nullable=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "policies", "updated_at", existing_type=sa.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "policies", "created_at", existing_type=sa.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "persons", "updated_at", existing_type=sa.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "persons", "created_at", existing_type=sa.TIMESTAMP(), nullable=True
    )
    op.drop_column("persons", "version")
    op.alter_column(
        "permissions", "updated_at", existing_type=sa.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "permissions", "created_at", existing_type=sa.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "addresses", "updated_at", existing_type=sa.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "addresses", "created_at", existing_type=sa.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
